### PR TITLE
Changed all Callbacks in ModManager to Promises

### PR DESCRIPTION
**Pull request by Danacus**
It works now, but there is are some problems with the UI.

- The text message below when downloading mods appears when downloading the first mod, but then it slowly disappears after some seconds. Whenever I download a new mod, the message doesn't become visible again.
- The installation status of the mods in the online mod list doesn't update when downloading a mod, but it does update in the installed mods tab and the profiles tab.

I don't know if it's a big problem that the UI isn't working correctly, since you're rewriting it.

### CODE REVIEW

**Comment by Danacus** [comment]
I fixed the bugs. Maybe it's not the most proper way to fix it, but at least everything is working now.

**Comment by Danacus** [comment]
You can skip this pull request and go to https://github.com/AlyxMoon/Lunars-Factorio-Mod-Manager/pull/87 instead.

**Comment by AlyxMoon** [comment]
Sure, I'll give a more concrete response once I've had a chance to look through the code.

**Comment by Danacus** [comment]
Ok, that's fine. Don't hurry, take your time and take a look whenever you want.

**Comment by Danacus** [comment]
Actually I don't really care what you do with my pull requests, as long as I'm not bored it the holidays, it's fine for me. I'm just learning a lot right now, just by trying to "contribute".

**Comment by AlyxMoon** [comment]
Well, this has been open a long while.

I'm planning on reworking the app so I'll be closing this and the issues. I remember being pretty unhelpful and a bit of a jerk about you wanting to assist back in the day, so my apologies about that.

**Pull request closed without merging**
