### PR TITLE
Node factorio api integration

### PR DESCRIPTION
**Pull request by Danacus**
I've integrated node-factorio-api (https://github.com/Danacus/node-factorio-api) for downloading mods. I'll wait until you've finished React before I might integrate more of it. (I would like to make a better way to list online mods and check for updates without having to wait until all mods are fetched).

This includes the 2 previous pull requests, so you can choose if you would like to merge this one too, otherwise just merge 1 of the other pull requests (or none of them if you don't like them)

### CODE REVIEW

**Comment by AlyxMoon** [comment]
So I don't want to just be a grumpy jerk here, but I don't want to use that library, sorry.
This is still a bit of a pet project for me, and I do want to implement everything for this project. Seems like that repo you're doing will consist of all the core functionality of the mod manager, which is fine and sounds cool, but I want to make that logic.

And as another note, all of your pull requests have the same commits plus a little extra, which makes it a little weird if I were to pull in more than one. I know you're working at a much faster pace than I so you're able to run through stuff far quicker, but it was a bit odd seeing three pull requests with (at first) seemingly the same changes.

**Comment by Danacus** [comment]
Ok, that's fine

**Comment by Danacus** [comment]
I was going way to fast with implementing the library, before it was in a ready state and I didn't even ask you. Sorry for doing this and thank you for closing this pull request, it was definitely the right thing to do!

I understand you want to make that logic yourself, I like making it myself too, it's fun!
Maybe I'll make my own Mod Manager, just for fun!

**Comment by AlyxMoon** [comment]
You should! I definitely learned a lot building my project from the ground up. Plus you have a lot more time to code, don't get bogged down by my snail's pace :D

**Comment by Danacus** [comment]
I already started! xD. I started from scratch, no boilerplates, I want to learn everything! 

If you need any help, or you want me to compile linux packages for you, feel free to contact me!

Good luck with your project!

**Pull request closed without merging**
