### PR TITLE
Use react for client rendering

### PR DESCRIPTION
**Pull request by AlyxMoon**
It's finished! Restructured the client-side code to use React to render everything. The file structure got a bit chaotic but the code is better handled and a bit more responsive than before.

### CODE REVIEW

**Comment by Danacus** [comment]
Good job! I'm still learning React, so maybe I'll take a look at how you made it, if you don't mind.

**Comment by AlyxMoon** [comment]
Thanks, and yeah I don't mind at all, that's the benefit of Open Source!

**Comment by Danacus** [comment]
Thanks, my mod manager is open source too, but don't waste your time looking at the source code, it's still very chaotic.

**Comment by AlyxMoon** [comment]
Haha that's all part of the fun, hope you enjoy making it.

**Comment by Danacus** [comment]
Of course I enjoy making it! :) You probably enjoy making yours too. Why else would we do it? :D

**Pull request merged**
